import ZoneOracle

# Generated by scripts/generate_zone_oracle.py; pinned tzdata 2025.2 / IANA 2025b.
Cases :: [].{
	fixtures : List(ZoneOracle.Fixture)
	fixtures = [
		{ name: "Australia/Lord_Howe", source_digest: "f368bd25659c0293d02bb79ec7dac7d5b73a92dffafce14b4dd2ffb8ba11aada", lower: 1712016000000000, upper: 1712880000000000, initial: 39600, minimum: 36000, maximum: 41400, transitions: [{ at: 1712415600000000, offset: 37800 }] },
		{ name: "Australia/Lord_Howe", source_digest: "f368bd25659c0293d02bb79ec7dac7d5b73a92dffafce14b4dd2ffb8ba11aada", lower: 1727740800000000, upper: 1728604800000000, initial: 37800, minimum: 36000, maximum: 41400, transitions: [{ at: 1728142200000000, offset: 39600 }] },
		{ name: "Pacific/Apia", source_digest: "dc70c47c80ab2c87a1ab754bab8febfc38508059e249dfe55e73a3759808ea14", lower: 1324771200000000, upper: 1325635200000000, initial: -36000, minimum: -41400, maximum: 50400, transitions: [{ at: 1325239200000000, offset: 50400 }] },
	]
	inputs : List(ZoneOracle.Case)
	inputs = [
		{ id: 0, zone: 0, date: { year: 2024, month: 4, day: 6 }, clock: { hour: 0, minute: 0, second: 0, microsecond: 0 }, expected: [1712322000000000] },
		{ id: 1, zone: 0, date: { year: 2024, month: 4, day: 6 }, clock: { hour: 0, minute: 0, second: 0, microsecond: 1 }, expected: [1712322000000001] },
		{ id: 2, zone: 0, date: { year: 2024, month: 4, day: 6 }, clock: { hour: 0, minute: 0, second: 0, microsecond: 999999 }, expected: [1712322000999999] },
		{ id: 3, zone: 0, date: { year: 2024, month: 4, day: 7 }, clock: { hour: 1, minute: 30, second: 0, microsecond: 0 }, expected: [1712413800000000, 1712415600000000] },
		{ id: 4, zone: 0, date: { year: 2024, month: 4, day: 7 }, clock: { hour: 1, minute: 30, second: 0, microsecond: 1 }, expected: [1712413800000001, 1712415600000001] },
		{ id: 5, zone: 0, date: { year: 2024, month: 4, day: 7 }, clock: { hour: 1, minute: 30, second: 0, microsecond: 999999 }, expected: [1712413800999999, 1712415600999999] },
		{ id: 6, zone: 1, date: { year: 2024, month: 10, day: 5 }, clock: { hour: 0, minute: 0, second: 0, microsecond: 0 }, expected: [1728048600000000] },
		{ id: 7, zone: 1, date: { year: 2024, month: 10, day: 5 }, clock: { hour: 0, minute: 0, second: 0, microsecond: 1 }, expected: [1728048600000001] },
		{ id: 8, zone: 1, date: { year: 2024, month: 10, day: 5 }, clock: { hour: 0, minute: 0, second: 0, microsecond: 999999 }, expected: [1728048600999999] },
		{ id: 9, zone: 1, date: { year: 2024, month: 10, day: 6 }, clock: { hour: 2, minute: 0, second: 0, microsecond: 0 }, expected: [] },
		{ id: 10, zone: 1, date: { year: 2024, month: 10, day: 6 }, clock: { hour: 2, minute: 0, second: 0, microsecond: 1 }, expected: [] },
		{ id: 11, zone: 1, date: { year: 2024, month: 10, day: 6 }, clock: { hour: 2, minute: 0, second: 0, microsecond: 999999 }, expected: [] },
		{ id: 12, zone: 2, date: { year: 2011, month: 12, day: 29 }, clock: { hour: 0, minute: 0, second: 0, microsecond: 0 }, expected: [1325152800000000] },
		{ id: 13, zone: 2, date: { year: 2011, month: 12, day: 29 }, clock: { hour: 0, minute: 0, second: 0, microsecond: 1 }, expected: [1325152800000001] },
		{ id: 14, zone: 2, date: { year: 2011, month: 12, day: 29 }, clock: { hour: 0, minute: 0, second: 0, microsecond: 999999 }, expected: [1325152800999999] },
		{ id: 15, zone: 2, date: { year: 2011, month: 12, day: 30 }, clock: { hour: 0, minute: 0, second: 0, microsecond: 0 }, expected: [] },
		{ id: 16, zone: 2, date: { year: 2011, month: 12, day: 30 }, clock: { hour: 0, minute: 0, second: 0, microsecond: 1 }, expected: [] },
		{ id: 17, zone: 2, date: { year: 2011, month: 12, day: 30 }, clock: { hour: 0, minute: 0, second: 0, microsecond: 999999 }, expected: [] },
	]
}
