name: Update Roc nightly
on:
  schedule:
    - cron: '19 13 * * *'
  workflow_dispatch:
permissions: {}
concurrency:
  group: roc-nightly-update
  cancel-in-progress: false
jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
      actions: write
      statuses: write
    uses: lukewilliamboswell/roc-automation/.github/workflows/update-roc-nightly.yml@5e6663c1436f038a35cc076a1b2921983e9b954c
